"""First Revision

Revision ID: 2e288f504e59
Revises:
Create Date: 2022-02-24 12:21:39.851246

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2e288f504e59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skate_tricks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("fundamental", sa.Boolean(), nullable=False),
        sa.Column(
            "flip",
            sa.Enum("ollie", "kickflip", "heelflip", name="fliptype"),
            nullable=False,
        ),
        sa.Column(
            "board_rotation",
            sa.Enum("bs", "fs", name="rotationdirection"),
            nullable=True,
        ),
        sa.Column(
            "board_spin",
            sa.Enum("d180", "d360", "d540", "d720", name="spindegrees"),
            nullable=True,
        ),
        sa.Column(
            "body_rotation",
            sa.Enum("bs", "fs", name="rotationdirection"),
            nullable=True,
        ),
        sa.Column(
            "body_spin",
            sa.Enum("d180", "d360", "d540", "d720", name="spindegrees"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skate_tricks_fundamental"),
        "skate_tricks",
        ["fundamental"],
        unique=False,
    )
    op.create_index(op.f("ix_skate_tricks_name"), "skate_tricks", ["name"], unique=True)
    op.create_table(
        "variation_tricks",
        sa.Column("trick_id", sa.Integer(), nullable=False),
        sa.Column("fundamental_trick_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fundamental_trick_id"],
            ["skate_tricks.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trick_id"], ["skate_tricks.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("trick_id", "fundamental_trick_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variation_tricks")
    op.execute("DROP TYPE fliptype CASCADE")
    op.execute("DROP TYPE rotationdirection CASCADE")
    op.execute("DROP TYPE spindegrees CASCADE")
    op.drop_index(op.f("ix_skate_tricks_name"), table_name="skate_tricks")
    op.drop_index(op.f("ix_skate_tricks_fundamental"), table_name="skate_tricks")
    op.drop_table("skate_tricks")
    # ### end Alembic commands ###
